name: Ansible deploy

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Display Ansible Version
        run: | 
          ansible --version
          python --version
          python3 --version
         
      - name: Install pywinrm
        run: pip3 install pywinrm
        
      - name: Display Ansible Version
        run: | 
          pip show pywinrm
          pip3 show pywinrm
          
      - name: Navigate Home
        run: |
          pwd
          cd ~

      - name: Write Content to File
        run: |
          echo '---' > ~/variables.yml
          echo 'dockerhub_username: Oliver' >> ~/variables.yml
          echo 'dockerhub_password: Pass123word' >> ~/variables.yml
          echo 'app_name: App' >> ~/variables.yml
          echo 'app_version: Ver' >> ~/variables.yml
 
      - name: Show File Contents
        run: cat ~/variables.yml
